import { NextPage, GetServerSideProps, InferGetServerSidePropsType } from "next"
import Head from "next/head"
import Link from "next/link"
import styles from "../styles/Home.module.css"

type Data = { 
    message: string;
};

function Home({ data } : InferGetServerSidePropsType<typeof getServerSideProps>) {
    return (
        <div className={styles.container}>
            <Head>
                <title>slidr</title>
                {/* <meta name="description" content="Generated by create next app" /> */}
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>

            <p>{ data["message"] }</p>
            <h1 className={styles.logo}>slidr</h1>
            <div>
                <Link href="/login"><a>Login</a></Link>
                <Link href="/register"><a>Register</a></Link>
            </div>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps = async () => {
    const res = await fetch("http://localhost:8080/api/message");
    const data: Data = await res.json();

    return {
        props: {
            data,
        },
    }
}

export default Home
